### ISSUE TITLE
Sending commands that take long compute time crashes Minecraft server

### ISSUE THREAD

**Issue by daxm** [barneygale/MCRcon#14]
Running the following code will crash the Minecraft server.  My guess is that the Minecraft server is still parsing the result of the executed command and the "connect()" function quits too soon.

```
import mcrcon
server = mcrcon.MCRcon(host='x.x.x.x', port=25575, password='asdf')
server.connect()
server.command('/fill 639995 11 639995 640069 15 640069 water replace')
```

Possibly adding a "waittime" variable to pass with the connect() function could solve this?

**Comment by kiriharu** [comment]
I think your guess is not true, run this command in console and post your answer again.

**Comment by daxm** [comment]
> 
> 
> I think your guess is not true, run this command in console and post your answer again.

What command?

**Comment by barneygale** [comment]
Timing issues are solved in the latest commit
