### ISSUE TITLE
in_id, in_type = struct.unpack("<ii", in_payload[:8]) struct.error: unpack requires a buffer of 8 bytes

### ISSUE THREAD

**Issue by ffuyu** [barneygale/MCRcon#20]

**Comment by owoqq** [comment]
another rcon module (python-valve) also raises the same error. tried with different python versions

**Comment by mncrftfrcnm** [comment]
how did you solve that?

**Comment by ffuyu** [comment]
Hey, it’s been years and I don’t really remember. You could refer to demo.py though as it seems you need to pass sock as the first argument and then the command.

**Comment by mncrftfrcnm** [comment]
Thank you, @f11y11
